module.exports = {
  COMMON_CODE_GROUP: {
  },
  COMMON_CODE: {
  },
  PUSH_MESSAGE: {
    TITLE: '일순간',
    MESSAGE: {
      ARTICLE: 'MESSAGE_1',
    },
  },
  DEFAULT_PAGING_OFFSET: 0,
  DEFAULT_PAGING_LIMIT: 20,
  DEFAULT_GROUP_LIMIT: 5,
  ADMIN_LOGIN_TOKEN: 'ADMIN_LOGIN_TOKEN',
  ADMIN_LOGIN_TERM: 60 * 1000 * 180,
  MAX_ALARM_DAY: 10,
  MAX_ALARM_COUNT: 3,
};
